<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="enquiryFollowupForm.aspx.cs" Inherits="DxConsistent.views.trans.child.enquiryFollowupForm" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Enquiry Followup form</title>
</head>
<body>

    <form id="formEnquiryFollowupForm" class="formEnquiryFollowupForm" runat="server">
        <div class="card card-primary card-outline direct-chat direct-chat-primary mt-3">
            <div class="card-header">
                <h3 class="card-title">Follow up Entry</h3>
                <div class="card-tools">
                </div>
            </div>
            <div class="card-body">
                <input type="hidden" id="hRV" name="hRV" class="hRV" value="" runat="server" />
                <input type="hidden" id="hEnquiryId" runat="server" value="0" />
                <input type="hidden" id="hAction" runat="server" value="0" />
                <input type="hidden" id="hCustomerId" runat="server" value="0" />
                <div class="form-horizontal">
                    <div class="form-btn-group row">
                        <div class="col-md-6">
                            <div class="row">
                                <div class="col-md-4">
                                    <label class="col-form-label">Branch<span class="text-danger">*</span></label>
                                </div>
                                <div class="col-md-8">
                                    <select id="ddlArea" class="form-control form-control-sm select3" runat="server"></select>
                                </div>
                                <div class="col-md-4">
                                    <label class="col-form-label">Lead Generated By<span class="text-danger">*</span></label>
                                </div>
                                <div class="col-md-8">
                                    <select id="ddlLeadGeneratedBy" class="form-control form-control-sm select3" runat="server"></select>
                                </div>
                                <div class="col-md-4">
                                    <label class="col-form-label">Lead Assign To<span class="text-danger">*</span></label>
                                </div>
                                <div class="col-md-8">
                                    <select id="ddlAssignTo" class="form-control form-control-sm select3" runat="server"></select>
                                </div>
                                <div class="col-md-4">
                                    <label class="col-form-label">Billing Type<span class="text-danger">*</span></label>
                                </div>
                                <div class="col-md-8">
                                    <select id="ddlBillingType" class="form-control form-control-sm select3" runat="server"></select>
                                </div>
                                <div class="col-md-4">
                                    <label class="col-form-label">Enquiry Flow<span class="text-danger">*</span></label>
                                </div>
                                <div class="col-md-8">
                                    <select id="ddlEnquiryFlow" class="form-control form-control-sm select3" runat="server"></select>
                                </div>
                                <div class="col-md-4">
                                    <label class="col-form-label">Partner Type<span class="text-danger">*</span></label>
                                </div>
                                <div class="col-md-8">
                                    <select id="ddlPartnerType" class="form-control form-control-sm select3" runat="server"></select>
                                </div>
                                
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="row"><div class="col-md-4">
                                    <label class="col-form-label">Company Name<span class="text-danger">*</span></label>
                                </div>
                                <div class="col-md-8">
                                    <input type="text" runat="server" id="txtCompanyName" class="form-control form-control-sm txtCompanyName" maxlength="100" autocomplete="off" />
                                </div>
                                <div class="col-md-4">
                                    <label class="col-form-label">Contact Person<span class="text-danger">*</span></label>
                                </div>
                                <div class="col-md-8">
                                    <input type="text" runat="server" id="txtContactPerson" class="form-control form-control-sm txtContactPerson" maxlength="100" autocomplete="off" />
                                </div>
                                <div class="col-md-4">
                                    <label class="col-form-label">Contact No<span class="text-danger">*</span></label>
                                </div>
                                <div class="col-md-8">
                                    <input type="text" id="txtContactNo" class="form-control form-control-sm mobileNo txtContactNo" maxlength="10" autocomplete="off" runat="server" />
                                </div>
                                <div class="col-md-4">
                                    <label class="col-form-label">Email Id</label>
                                </div>
                                <div class="col-md-8">
                                    <input type="text" runat="server" id="txtEmailId" class="form-control form-control-sm txtEmailId" maxlength="500" autocomplete="off" />
                                </div>
                                <div class="col-md-4">
                                    <label class="col-form-label">Enquiry Type<span class="text-danger">*</span></label>
                                </div>
                                <div class="col-md-8">
                                    <select id="ddlEnquiryType" class="form-control form-control-sm select3" runat="server"></select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group row" id="dvProduct">
                        <div class="col-md-12">
                            <h6 class="text-danger pt-2">Products</h6>
                            <table id="tblProduct" class="table-striped table-bordered table-condensed" style="width: 100%">
                                <thead>
                                    <tr class="text-dark">
                                    </tr>
                                    <tr class="text-dark">
                                        <th style="width: 5%;" class="text-center">SNO</th>
                                        <th style="width: 45%;" class="pl-2 pr-2">PRODUCT</th>
                                        <th style="width: 10%;" class="pl-2 pr-2 text-right">QTY</th>
                                        <th style="width: 15%;" class="pl-2 pr-2 text-right">RATE</th>
                                        <th style="width: 15%;" class="pl-2 pr-2 text-right">TOTAL</th>
                                        <th style="width: 3%;" class="pl-2 pr-2 text-right"></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <asp:Repeater ID="repProduct" runat="server">
                                        <ItemTemplate>
                                            <tr class="trm" style="background-color: white" id="trm<%# Container.ItemIndex %>">
                                                <td class="text-center"><%# Container.ItemIndex+1 %> </td>
                                                <td>
                                                    <input type="hidden" name="hProductId" class="hProductId" value="<%# Eval("ProductId") %>" />
                                                    <div id="scrollable-dropdown-menu">
                                                        <input type="text" class="form-control form-control-sm no-border txtProductName" placeholder="Search Product" autocomplete="off" maxlength="100" value="<%# Eval("ProductName") %>" />
                                                    </div>
                                                </td>
                                                <td>
                                                    <input type="text" class="form-control form-control-sm no-border txtQty numberOnly" placeholder="0" autocomplete="off" maxlength="5" onkeyup="calculateAmt()" value="<%# Eval("Qty") %>" />
                                                </td>
                                                <td>
                                                    <input type="text" class="form-control form-control-sm no-border txtRate currency" placeholder="0" autocomplete="off" maxlength="10" onkeyup="calculateAmt()" value="<%# Eval("Rate") %>" />
                                                </td>
                                                <td>
                                                    <input type="text" class="form-control form-control-sm no-border txtAmount currency" placeholder="0" autocomplete="off" maxlength="12" disabled="disabled" onkeyup="calculateAmt()" value="<%# Eval("Amount") %>" />
                                                </td>
                                                <td class="float-center">
                                                    <button type="button" onclick="removeProduct(this);" class="close" aria-label="Close"><span aria-hidden="true" style="width: 22%; color: black; text-align: center">&times;</span></button>
                                                </td>
                                            </tr>
                                        </ItemTemplate>
                                    </asp:Repeater>
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <td colspan="4" class="text-center; bg-lime" style="text-align: center"><b>TOTAL</b></td>
                                        <td class="text-right;" style="text-align: right; background-color: yellow; color: black"><span id="spnTotalAmt" style="font-weight: bold; padding-right: 5px">0.0</span></td>
                                    </tr>
                                    <tr>
                                        <td colspan="6" style="text-align: right" class="text-right">
                                            <a id="btnAddProduct" class="bg-gradient-info pull-right margin-0s btn-xs"
                                                href="javascript:void(0);" onclick="return addProduct();">Add Product</a>
                                        </td>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-12">
                            <label class="col-form-label">Remarks</label>
                            <textarea id="txtRemarks" runat="server" class="form-control form-control-sm textArea" aria-autocomplete="none" aria-expanded="false"></textarea>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn bg-gradient-primary ladda-button" data-style="zoom-in" id="btnSubmitChild">Save Changes</button>
                    <button type="reset" class="btn btn-default" id="btnCancel" data-dismiss="modal">Cancel</button>
                </div>
            </div>
        </div>
    </form>
    <script>
        $(document).ready(function () {
            IsEdit = GetBoolValue($(".hIsEdit")); IsDelete = GetBoolValue($(".hIsDelete"));
            hUserId = GetCtrlIntVal($(".hUserId")); IsExport = GetBoolValue($(".hIsExport"));
            $(".select3").select2();
            $('.datepicker').daterangepicker({}, function (start, end, label) { mainGrid.dxDataGrid("instance").refresh(); });
            $(".ddlEnquiryStatus").on("change", function () { mainGrid.dxDataGrid("instance").refresh(); });
        });
    </script>
</body>
</html>
